trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover -s tests
  displayName: 'Run tests'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students'
    appName: 'HeimlichTrainerIA'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.8'
