trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt -t .python_packages/lib/site-packages
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover -s tests
  displayName: 'Run tests'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'your-azure-subscription'
    appName: 'your-app-name'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.8'
